### ISSUE TITLE
Extend the current EDCs configuration in BDRS

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/tractus-x-umbrella#146]
## Description

- Create more edcs in the umbrella.
- Register EDCs with BDRS integration

**Comment by mgarciaLKS** [comment]
Questions related to this issue:

1. How many more EDCs you want to create, ¿consumers or providers?
2. Create a new adopter where all the connectors can be enabled or add them to the existing ones
3. How are the tests supposed to work, provider1 can exchange data with consumer1, consumer2, consumer3. Provider2 with consumer1, etc. because this would not only greatly increase the number of lines of code, but also slow down the tests enormously.

**Comment by matbmoser** [comment]
Maybe 10 edcs should be enought for a first test drive. But we want to be able to register edcs automatically here #145, you can also support us there.

**Comment by mgarciaLKS** [comment]
Hello @matbmoser. I have added two new connectors, one Provider, and one Consumer in the next [Fork](https://github.com/mgarciaLKS/tractus-x-umbrella/tree/connectorTest).
The main things to do are the following ones:
:warning: _don't forget to add the new connectors to the /etc/hosts_
- values.yaml
Take one of the BPNs in the BDRS that are not being used, and use them in the new added connectors, for example, the provider:
```
tx-data-providerOne:
  enabled: false
  seedTestdata: true
  backendUrl: http://{{ .Release.Name }}-dataproviderone-submodelserver:8080
  registryUrl: http://{{ .Release.Name }}-dataproviderone-dtr:8080/api/v3
  controlplanePublicUrl: http://{{ .Release.Name }}-dataproviderone-edc-controlplane:8084
  controlplaneManagementUrl: http://{{ .Release.Name }}-dataproviderone-edc-controlplane:8081
  dataplaneUrl: http://{{ .Release.Name }}-dataproviderone-edc-dataplane:8081
  nameOverride: dataproviderone
  secrets:
    edc-wallet-secret: changeme
  tractusx-connector:
    nameOverride: dataproviderone-edc
    participant:
      id: BPNS00000008BDFH
    iatp:
      id: did:web:ssi-dim-wallet-stub.tx.test:BPNS00000008BDFH
      trustedIssuers:
        - did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003CRHK
      sts:
        dim:
          url: http://ssi-dim-wallet-stub.tx.test/api/sts
        oauth:
          token_url: http://ssi-dim-wallet-stub.tx.test/oauth/token
          client:
            id: BPNS00000008BDFH
            secret_alias: edc-wallet-secret
...
```

- Chart.yaml
Add all the connector you want to use:
```
   # TX Data Providers 1
  - name: tx-data-provider
    alias: tx-data-providerOne
    version: 0.1.1
    repository: file://../tx-data-provider
    condition: tx-data-providerOne.enabled
    # TX Data Consumer 3
  - name: tx-data-provider
    alias: dataconsumerThree
    version: 0.1.1
    repository: file://../tx-data-provider
    condition: dataconsumerThree.enabled
```

- values-adopter-data-exchange.yaml
Enable the new connectors to test them
```
dataconsumerThree:
  enabled: true
    # -- uncomment the following for persistence
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true

tx-data-providerOne:
  seedTestdata: true
  enabled: true
  # -- uncomment the following for persistence
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true
  # digital-twin-registry:
  #   postgresql:
  #     primary:
  #       persistence:
  #         enabled: true
```
![image](https://github.com/user-attachments/assets/6f44ea01-bee6-4e36-912b-1ed890c135a3)
![image](https://github.com/user-attachments/assets/aa6b4992-b17b-44e0-9c3e-f9c7c1cba263)
![image](https://github.com/user-attachments/assets/88c5f8dd-3501-4e55-a3cb-102a15a30993)
