### ISSUE TITLE
Unable to fetch client secret from vault

### ISSUE THREAD

**Issue by kss682** [eclipse-tractusx/tractus-x-umbrella#274]
We are having a setup with 2 EDC, one provider (with bpdm) and one consumer. To test our set up, we ran the postman collections from the bpdm docs. We were successful in running the provider collection but faced challenges with the consumer collection. 

The following error is shown: 

![Image](https://github.com/user-attachments/assets/a63fe381-bd81-483a-b0ed-afd5d1fbbcb7)

We have a vault running but have doubts regarding where the endpoint of the vault should be configured for it to read from the correct path. 

Changing these configurations in the postman provider collection did not help too, the error still shows that it is trying to access `vault/path/client/1/secret`

![Image](https://github.com/user-attachments/assets/1f97dd12-2d34-4bf4-90a0-33dc74a478f9)

Could you please help us understand what we have missed ?

**Comment by mgarciaLKS** [comment]
Hello @kss682 
Have you changed the following configuration? https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/main/charts/umbrella/values.yaml#L1122

**Comment by kss682** [comment]
Hello @mgarciaLKS , 
Yes, we have changed it to point to our url

![Image](https://github.com/user-attachments/assets/f9193c68-0f76-43ba-8e46-3a74527461bb)

**Comment by evegufy** [comment]
Hi @kss682 the error is quite certainly not in the default configuration from the umbrella, as it can't be reproduced there and is somewhere in your configuration changes to fit this bdpm case you'd like to test/provided: so, the provided information is not enough to support here, please provide all the changes you did in comparison to the default umbrella config.

**Comment by kss682** [comment]
@evegufy  Our configuration file is quite huge (over 1000 lines), would just a part of the config suffice ? 
In this case, I assume the config changes of hashicorp would be sufficient . 

```
    [... data plane config above.. ]
    vault:
      hashicorp:
        url: http://bpdm-edc-provider-vault:8200
      secretNames:
        transferProxyTokenSignerPrivateKey: tokenSignerPrivateKey
        transferProxyTokenSignerPublicKey: tokenSignerPublicKey
        transferProxyTokenEncryptionAesKey: tokenEncryptionAesKey

  vault:
    nameOverride: bpdm-edc-provider-vault
    fullnameOverride: bpdm-edc-provider-vault
    enabled: true
    server:
      postStart: []
```
